name: playground

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  Play:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: DotNetBuild
        uses: snigdhasjg/firebase-server-demo/.github/actions/DockerRun@main
        with:
          image: mcr.microsoft.com/dotnet/sdk
          version: 7.0-jammy
          inline_script: |
            dotnet restore firebase-server-demo.csproj
            dotnet publish firebase-server-demo.csproj -c Release -o ./publish

            ls -ltra publish
