name: playground

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  Play:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: DotNetBuild
        uses: snigdhasjg/firebase-server-demo/.github/actions/DockerRun@main
        run: |
          dotnet restore firebase-server-demo.csproj
          dotnet publish firebase-server-demo.csproj -c Release -o ./publish

          ls -ltra publish
